### ISSUE TITLE
Target word markup problem

### ISSUE THREAD

**Issue by Vitaly-Protasov** [akutuzov/rushifteval_public#1]
As I noticed, there are __223__(only for `rusemshift1_raw_annotations.tsv`) sentences, which are without `<b><i>` tag near the target word.
For example in:
```
Unnamed: 0                                                 2905
word                                                       ядро
sent1         Несколько ядер с визгом шмыгнуло уже мимо нас;...
sent2         В течение более чем 1000 часов облучения при р...
mean                                                          1
annotator1                                                    1
annotator2                                                    1
annotator3                                                    1
Name: 2905, dtype: object Несколько ядер с визгом шмыгнуло уже мимо нас; несмотря на то, чайники кипели, и нам, уже стоявшим в строю, поднесли несколько стаканов чаю с ржаными сухарями.
```

**Comment by akutuzov** [comment]
Hi, thanks for noticing.
This is expected: the HTML tags around target words were injected by an external function which used an extremely simplistic stemming method.
This does not influence the dataset itself in any way: these HTML tags were there only to help the annotators a bit.

**Comment by Vitaly-Protasov** [comment]
@akutuzov  By the way, don't you mind if I fix it ? :)

**Comment by akutuzov** [comment]
@Vitaly-Protasov certainly, pull requests are welcome!
